import { expect, test } from '@playwright/test';
import { chooseOpening, gamePoint, openApp } from './helpers';

test('first practice follows real selection, movement and ship production; skips persist', async ({ page }) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 1366, height: 768 });
  await openApp(page, '/?testTimeScale=2&testSeed=42');
  await page.getByLabel('Identificador de comandante').fill('Nova');
  await page.getByRole('button', { name: 'Continuar como invitado' }).click();
  await page.getByRole('button', { name: /Preparar operación/ }).click();
  await page.getByRole('button', { name: /^Fácil/ }).click();
  await page.getByLabel('Estoy listo para desplegar').check();
  await page.getByRole('button', { name: 'Iniciar operación' }).click();
  await chooseOpening(page);
  await expect(page.locator('.vi-phaser')).toHaveAttribute('data-ready', 'true');
  const guide = page.getByRole('region', { name: 'Primera práctica' });
  await expect(guide).toHaveAttribute('data-step', 'select');
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByRole('region', { name: 'First practice' })).toContainText('Select your fleet');
  await page.getByRole('button', { name: 'ES', exact: true }).click();
  const ship = await gamePoint(page, 12, 11);
  await page.mouse.click(ship.x, ship.y - 12);
  await expect(guide).toHaveAttribute('data-step', 'move');
  const destination = await gamePoint(page, 12, 14);
  await page.mouse.click(destination.x, destination.y, { button: 'right' });
  await expect(guide).toHaveAttribute('data-step', 'produce');
  await page.locator('.vi-production__unit').last().getByRole('button').click();
  await expect(guide).toHaveAttribute('data-step', 'capture');
  await expect(guide).toContainText('Los Exploradores no capturan');
  await page.screenshot({ path: 'test-results/first-practice-tutorial.png' });
  await guide.getByRole('button', { name: 'Saltar paso' }).click();
  await expect(guide).toHaveAttribute('data-step', 'refinery');
  await guide.getByRole('button', { name: 'Omitir tutorial' }).click();
  await expect(guide).toHaveCount(0);
  expect(await page.evaluate(() => localStorage.getItem('impulso.first-match-tutorial.v1'))).toBe('seen');
  await page.getByRole('button', { name: 'Salir de simulación' }).click();
  await page.reload();
  await page.getByLabel('Identificador de comandante').fill('Nova');
  await page.getByRole('button', { name: 'Continuar como invitado' }).click();
  await page.getByRole('button', { name: /Preparar operación/ }).click();
  await page.getByLabel('Estoy listo para desplegar').check();
  await page.getByRole('button', { name: 'Iniciar operación' }).click();
  await chooseOpening(page);
  await expect(page.locator('.vi-tutorial')).toHaveCount(0);
});
