/** Lines that surface in the lobby's interference while Trascendencia Estelar is selected. Edit freely. */
export const ANOMALY_WORDS: readonly string[] = [
  // The Stellar network
  'QUORUM SLICE', 'LEDGER CLOSED', 'CONSENSUS FAILURE', 'TRANSACTION CONFIRMED', 'STELLAR CONSENSUS PROTOCOL',
  'VALIDATOR OFFLINE', 'NOMINATION ROUND', 'BALLOT ABORTED', 'EXTERNALIZE', 'HORIZON TIMEOUT', 'SEQUENCE MISMATCH',
  'TRUSTLINE REVOKED', 'LUMENS DRAINED', 'ANCHOR LOST', 'tx_bad_seq', 'op_no_trust', 'SOROBAN TRAP',
  // The four nodes
  'NODE I — MEMORY', 'NODE II — WILL', 'NODE III — ENERGY', 'NODE IV — CONSENSUS',
  'NODE 01 ONLINE', 'NODE 02 ONLINE', 'NODE 03 ERROR', 'NODE 04 ERROR',
  // What is coming through
  '⚠ ANOMALY DETECTED', '⚠ GRAVITATIONAL DISTORTION', 'EXTREME THREAT', 'LEVIATHAN // NULL', 'THE CONSENSUS DEVOURER',
  'NULL CONSENSUS', 'SINGULARITY', 'STELLAR COLLAPSE', 'SIGNAL ORIGIN: UNKNOWN', 'ACCESS OVERRIDDEN',
];
